### ISSUE TITLE
Convert two assignment statements to augmented source code

### ISSUE THREAD

**Issue by elfring** [git-big-picture/git-big-picture#156]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

```diff
diff --git a/git_big_picture/_main.py b/git_big_picture/_main.py
index f8ae22a..bdf5fef 100755
--- a/git_big_picture/_main.py
+++ b/git_big_picture/_main.py
@@ -968,10 +968,10 @@ class CommitGraph:
                 labels = []
                 case = 0
                 if k in self.tags:
-                    case = case + 1
+                    case += 1
                     labels.extend(sorted(self.tags[k]))
                 if k in self.branches:
-                    case = case + 2
+                    case += 2
                     labels.extend(sorted(self.branches[k]))
                 # http://www.graphviz.org/doc/info/colors.html
                 color = "/pastel13/%d" % case
```

**Comment by hartwork** [comment]
Hi @elfring, I somehow missed this ticket. Are you interested in turning this into a pull request against latest `master`?

**Comment by elfring** [comment]
:thought_balloon: Can the chances grow to integrate the shown tiny source code improvement also directly (with support from other contributors eventually)?

**Comment by hartwork** [comment]
@elfring, alright, I can turn that into a pull request for you and have the commit be in your name. Let me be clear though, that this will be an exception — let's not do more of these: the change does not fix a bug and the cost benefit ratio is not ideal. True bug reports (and fixes) are a better use of everyone's time, in my view. Thanks for your understanding.

PS: @esc may have a slightly different view (or not), I'm not speaking for him but only for myself at the moment.
