### ISSUE TITLE
RFE: --reduce / --simplify / --clean option (invokes tred)

### ISSUE THREAD

**Issue by edsantiago** [git-big-picture/git-big-picture#180]
On a large active repo, the visualization can be unmanageable. `tred` (part of graphviz) can be a lifesaver, converting an unreadable mess into a nice clean view. It is trivial to run it manually:
```console
$ git big-picture --history-direction rightwards -g | tred | dot -Tpng -ofoo.png
```
...but it seems the sort of thing that many people would appreciate as a standard option. 

Sample results:

Original: ![git-big-picture lr](https://user-images.githubusercontent.com/265639/155386958-91deec42-88e9-48cd-b5e2-a6c9e2314639.png)

With tred: ![git-big-picture-reduced](https://user-images.githubusercontent.com/265639/155387004-04fa60a3-e990-4621-bbff-2e50e0614ed7.png)

**Comment by hartwork** [comment]
Hi @edsantiago thanks for bringing `tred` to my attention and for the visual report. So it removes transitive edges and that simplifies the graph — interesting! I'm not sure a about the best name for this option, but your report sure is convincing that we should lower the bar for access to this feature.

**Comment by hartwork** [comment]
Let me record what it would take to complete this feature:
- a new commend line option
- code to transform content of variable `dot_file_lines` right before line `if output_settings[GRAPHVIZ]:` to affect both rendered and unrendered dotfile output
- dedicated tests
- a happy CI after

**Comment by esc** [comment]
👍 sounds useful!

**Comment by hartwork** [comment]
I have a first draft at #182, plan to finish in the coming days.

**Comment by hartwork** [comment]
@edsantiago this features just hit PyPI with release 1.2.0 — https://pypi.org/project/git-big-picture/1.2.0/

**Comment by edsantiago** [comment]
Thank you for your quick work!

**Comment by hartwork** [comment]
@edsantiago I should note that `--history-direction rightwards` is also the default now since #184 .
