### ISSUE TITLE
Request: A tar release

### ISSUE THREAD

**Issue by RandallFlagg** [git-big-picture/git-big-picture#380]
Can you please create a tar.gz/tar.xz release in addition to the source?
That way it will be usable on any Linux distro regardless if the package exists or not.

thanks

**Comment by hartwork** [comment]
Hi @RandallFlagg I'm not sure I understand the scenario — https://github.com/git-big-picture/git-big-picture/archive/refs/tags/v1.2.2.tar.gz does not work? What more is needed and for which scenario?

**Comment by RandallFlagg** [comment]
Thanks. That is great. My problem was that I expected to see there something a bit different with a less miss leading name as source code.
I know it is said in the README that you can just clone but the name got me confused.

Maybe it can be more clear when you come to download.

Thanks again.
