### ISSUE TITLE
Replace nose testing dependency

### ISSUE THREAD

**Issue by esc** [git-big-picture/git-big-picture#63]
The `nose` testing framework is dead. Need a replacement, either bare `unittest` or `pytest`?

**Comment by hartwork** [comment]
I see! I'd be okay with either for a runner. If you go for pytest, let's agree to only use pytest for a runner and to not turn the testsuite pytesty on the inside (e.g. because it raises the bar of entry by quite a bit). Would that be okay?

**Comment by esc** [comment]
That would be okay, yes. 

On 4 January 2021 22:06:09 CET, Sebastian Pipping <notifications@github.com> wrote:
>I see! I'd be okay with either for a runner. If you go for pytest,
>let's agree to only use pytest for a runner and to not turn the
>testsuite pytesty on the inside (e.g. because it raises the bar of
>entry by quite a bit). Would that be okay?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/git-big-picture/git-big-picture/issues/63#issuecomment-754218527

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
