### ISSUE TITLE
Decide on what to do with remaining TODO in README

### ISSUE THREAD

**Issue by esc** [git-big-picture/git-big-picture#77]
https://github.com/git-big-picture/git-big-picture#todo

For the first one, I don't even know what I meant anymore. The second is about allowing to abbreviate commit IDs? In any case, I think it would be fine if we delete them. 

What do you think?

**Comment by hartwork** [comment]
Sound good.

Looking at https://github.com/git-big-picture/git-big-picture/blob/3291cdb43baa0c7461073e8524dffffbf5297902/git_big_picture/_main.py#L902-L909 I think we'd only need `--abbrev=<number>` if someone wants to *enforce a specific above-minimal number of digits*. I think we can wait for people to ask for that to see if anyone actually needs it.

tldr: Go ahead! :+1:

**Comment by hartwork** [comment]
PS: I meant tag `obsolete` to mark an *issue* as obsolete which this ticket itself does not seem to be, to me. If we both read the tag different ways, let's rename it to be less easy to be interpreted differently?!

**Comment by esc** [comment]
@hartwork oh, I see what you mean, to declare PRs and Issues that are no longer needed, not to declare that the issue relates to the removal of something else that is obsolete. I get it now.

**Comment by esc** [comment]
Whoopsi, accidentally clicked the wrong button, my bad.
