### ISSUE TITLE
Documentation does not explain what a "bifurcation" is

### ISSUE THREAD

**Issue by hartwork** [git-big-picture/git-big-picture#84]
@esc it would be awesome if we explained somewhere what a "bifurcation" is, maybe ideally right at `--help` output. I myself still don't really know what a bifurcation after skip-reading https://en.wikipedia.org/wiki/Bifurcation_theory . I haven't tried too hard yet, but ideally that wouldn't be necessary. Can you take over?

**Comment by esc** [comment]
How about: "a bifurcation commit is a commit with two or more descendants", it is a bit like the opposite of a merge-commit, in a way.

**Comment by hartwork** [comment]
PS: Should this go in or after 1.1.0? I'm asking because of #81.

**Comment by esc** [comment]
I think, since the change is quite minimal we can get that in sooner rather than later?

**Comment by hartwork** [comment]
Good plan (and I'm happy to extend #81) but #80 should go in first either way so we won't need to fix conflicts or have broken CI on master.
