### ISSUE TITLE
"python" not necessarily available for cram test

### ISSUE THREAD

**Issue by d-torrance** [git-big-picture/git-big-picture#88]
The following cram test fails in Debian because `/usr/bin/python` doesn't exist<sup>1</sup>: 

https://github.com/git-big-picture/git-big-picture/blob/18ab133437ad5bc192e57d1222936912090c8613/test.cram#L39-L42

It looks like it may be okay to just switch it to `python3` instead (see, for example https://stackoverflow.com/questions/62214293/is-python3-always-installed-with-python-3).

<sup>1</sup>Unless the `python-is-python3` package is installed, but that's not supposed to be used when building packages -- see [Debian bug #973011](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973011).

**Comment by hartwork** [comment]
Hi @d-torrance thanks for reporting this issue! I'm happy with you or me creating a tiny pull request fixing this issue. Please let me know your preference. Best, Sebastian

**Comment by d-torrance** [comment]
> Hi @d-torrance thanks for reporting this issue! I'm happy with you or me creating a tiny pull request fixing this issue. Please let me know your preference. Best, Sebastian

No problem!  I went ahead and opened #89 with the suggested fix.
